name = "media-proxy"
main = "src/index.ts"
compatibility_date = "2024-06-15"
compatibility_flags = ["nodejs_compat"]

# 自定义域名配置（可选）
# routes = [
#   { pattern = "media-proxy.your-domain.com/*", zone_name = "your-domain.com" }
# ]

# 环境变量（如果需要）
[vars]
# PROXY_SECRET = "your-secret-key"

# 开发环境配置
[env.development]
name = "media-proxy-dev"

# 生产环境配置  
[env.production]
name = "media-proxy-prod"
